### ISSUE TITLE
Prepare the final catalogue of requirements

### ISSUE THREAD

**Issue by MDemovic** [TIS2024-FMFI/inspection#1]
Review the client's requirements and draft a comprehensive document based on them.

**Comment by ReinHeist** [comment]
Vytvoril 2 dokumenty sk a en
Vytvoril kostru

**Comment by MDemovic** [comment]
Pripravil som prvú verziu požiadaviek

**Comment by lilo02** [comment]
Upravila som všetky povodne časti na zaklade komunikacie z klientom

**Comment by RichardMacko** [comment]
Upravil som requirements na základe požiadaviek a komunikácii s klientom

**Comment by MDemovic** [comment]
Ja a @ReinHeist sme preložili Slovensku verziu do angličtiny

**Comment by ReinHeist** [comment]
2 linky na dokumenty
Sk verzia
https://docs.google.com/document/d/1K2rPoXctWUzwSfZGgFcfs5qYxZvOG7AeGyXmPYDD8hw/edit

En verzia

https://docs.google.com/document/d/1-gfFkbwWYdUdwpGbihi-Ikd_n5IA1A9ZH5nIMh2vMCQ/edit

**Comment by MDemovic** [comment]
Dostali sme dalsie poznámky od cvičiaceho ktoré musíme zapracovať do katalógu.

- the superviser revised our requirements catalogue
- barcode accepted with the client so we can progress from there
- the use is for general public
- the site will not change, but more defective products can be added, from both websites
- clarify in the requirements that we are scraping both websites and adding them into a list ...
- if defective show description,if not defective show only its not defective, since we dont have acces to the information to that product
- if logged in he can save, if not just check and not save.

**Comment by MDemovic** [comment]
Kvázi tieto veci musíme popridávať a môžeme posielať

**Comment by pavelpetrovic** [comment]
Ahojte, pozrel som si anglicky dokument, ale mam tiez pripomienku...
V tretej casti treba, aby bolo vsetko. Vy ste cast poziadaviek zaradili do 2. casti a cast do 3. casti.
Presunte vsetko do 3. casti. 
V druhej casti poziadavky najhradte plynulym textom, ktory ked si clovek precita, tak ziska pribliznu predstavu, co system bude robit.

**Comment by MDemovic** [comment]
Dobre, upravíme to tak 👍

**Comment by ReinHeist** [comment]
-Pridal do 3 kapitoly 17.The user can search for products by name or special attributes. The system also provides the possibility to filter the search results
-zmenil cast 2.2

**Comment by MDemovic** [comment]
Začnem robiť ďalšie úpravy

**Comment by MDemovic** [comment]
Posunul som tento issue do testingu - prosim skontrolujte či som jasne zapracoval všetky požiadavky @ReinHeist @lilo02 @RichardMacko a poopravoval nezrovnolosti. 

- Pridal som komentare co som kde zmenil
- Hlavne som este vymazal 2.4 a 2.5 a presunul to do req. Možno aj 2.3 by sme tam mohli presunut ale to si isty niesom

**Comment by lilo02** [comment]
Skontrolovala som a urobila posledné úpravy v katalógu

**Comment by MDemovic** [comment]
Ešte som upravil to znenie requirementu 13, nech je to jasné. 
Napíšem zadávateľovi na kontrolu.

**Comment by MDemovic** [comment]
Po stretnutí s cvičiacim posledný krát skontrolovali a dohodli na postupných úpravách. 
Sú v komentároch/označené červenou.

Najlepšie by bolo aby boli do zajtra poslané zadávateľovi.

**Comment by MDemovic** [comment]
Dokončil som tie updaty, všetci povinne pozrieť, následne pošlem zadávateľovi (aj supervizorovi znova pre istotu)

**Comment by MDemovic** [comment]
dostali sme od zadávatela zopar pripomienok ku nasim poziadavkam, ktore musime zapracovat do naseho dokumentu.

**Comment by MDemovic** [comment]
Katalóg požiadaviek bol upravený na základe feedbacku od zadávateľa.

**Comment by MDemovic** [comment]
We have finished the catalogue of requirements and we can proceed to the system design document
