### ISSUE TITLE
Finish minutes from the first and second supervisor meeting

### ISSUE THREAD

**Issue by MDemovic** [TIS2024-FMFI/inspection#2]

**Comment by MDemovic** [comment]
Rišo skús za dnešný meeting a ja urobím za prvý

**Comment by pavelpetrovic** [comment]
Nezabudnite, prosim, vsetky issues zaradit do projektu (vpravo "Projects" - vybrat Vas projekt) a potom v projekte sa uistite, ze vsetky listocky mate v spravnych stlpcoch.

Este dolezite - na Vasom pravidelnom stretnuti timu aj na stretnuti s cviciacim sa musia zucastnit vsetci clenovia timu, ak nemaju nejaky vazny dovod a nie su ospravedlneni, inak uctujeme -5% zo znamky za kazdu neospravedlnenu neucast.

**Comment by MDemovic** [comment]
@RichardMacko, dokočil som poznámky z druhého general meetingu a z druhého priority meetingu. 
Pripravil som ti kostru do tretieho priority meetingu. Použi poznámky priložené na konci isssue s katalógom. 
Absencie som popridával do všetkých poznámok.

**Comment by MDemovic** [comment]
Keby niečo iba editni predošle poznámky ak by si chcel nejaké odrážky alebo linky, alebo však mi napíš ak niečo

**Comment by RichardMacko** [comment]
Dokončil som poznámky z tretieho priority meetingu.
