### ISSUE TITLE
Create a general meeting record number 3

### ISSUE THREAD

**Issue by MDemovic** [TIS2024-FMFI/inspection#7]

**Comment by MDemovic** [comment]
Done

**Comment by pavelpetrovic** [comment]
You write minutes from the meeting directly to wiki at the meeting. 
In the beginning of the meeting, click NEW PAGE, at the end of the meeting click SAVE, and then you do not need to (and should not) touch it afterwards. Please realize that creating an issue for writing minutes from your regular meeting is just a useless spam. It is an automatic task. :)

**Comment by MDemovic** [comment]
@pavelpetrovic Sorry, won't happen again.
